server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:3001;
    }

    location /api/tasks/ {
        proxy_pass http://task-service:3002;
    }

    location /api/logs/ {
        proxy_pass http://log-service:3003;
    }
}
